plugin: aws_ec2
regions:
  - us-east-1 
filters:
  tag:Name: "technical-test-*" # Matches all instances starting with "technical-test-"
keyed_groups:
  - key: tags.Name
    prefix: "aws_"
hostnames:
  - tag:Name
compose:
  ansible_user: "'ec2-user'"
    #ansible_host: public_ip_address if tags.Name == 'technical-test-ariane' else private_ip_address 
  ansible_host: private_ip_address
